<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE model [
        <!ELEMENT model (palette|colorkeys|spritemap|layers|logic)*>
        <!ATTLIST model
                name CDATA #REQUIRED
                dir CDATA #REQUIRED
                width CDATA #REQUIRED
                height CDATA #REQUIRED
                scale CDATA #REQUIRED
                originX CDATA #IMPLIED
                originY CDATA #IMPLIED>
        <!ELEMENT palette (common|property)*>
        <!ELEMENT common (color)*>
        <!ELEMENT color (#PCDATA)>
        <!ATTLIST color
                name CDATA #REQUIRED>
        <!ELEMENT property (color)*>
        <!ATTLIST property
                default CDATA #REQUIRED
                name CDATA #REQUIRED
                src CDATA #REQUIRED>
        <!ELEMENT colorkeys (key)*>
        <!ELEMENT key (#PCDATA)>
        <!ATTLIST key
                base CDATA #REQUIRED
                src CDATA #REQUIRED
                transform CDATA #IMPLIED>
        <!ELEMENT spritemap (cell)*>
        <!ATTLIST spritemap
                file CDATA #REQUIRED>
        <!ELEMENT cell (#PCDATA)>
        <!ATTLIST cell
                dx CDATA #IMPLIED
                dy CDATA #IMPLIED
                name CDATA #REQUIRED
                rect CDATA #REQUIRED>
        <!ELEMENT layers (layer)*>
        <!ELEMENT layer (#PCDATA)>
        <!ATTLIST layer
                name CDATA #REQUIRED>
        <!ELEMENT logic (show|switch|if|hide|set)*>
        <!ELEMENT switch (case|default)*>
        <!ATTLIST switch
                value CDATA #IMPLIED>
        <!ELEMENT case (show|switch|if|hide|set)*>
        <!ATTLIST case
                test CDATA #IMPLIED
                value CDATA #IMPLIED
                values CDATA #IMPLIED>
        <!ELEMENT show (#PCDATA)>
        <!ATTLIST show
                part CDATA #REQUIRED>
        <!ELEMENT default (show|switch|if|hide|set)*>
        <!ELEMENT if (show|switch|if|hide|set)*>
        <!ATTLIST if
                test CDATA #REQUIRED>
        <!ELEMENT hide (#PCDATA)>
        <!ATTLIST hide
                part CDATA #REQUIRED>
        <!ELEMENT set (#PCDATA)>
        <!ATTLIST set
                var CDATA #REQUIRED
                value CDATA #IMPLIED>
        ]>
<!--suppress EqualityComparisonWithCoercionJS, CheckTagEmptyBody -->
<model name="demo" dir="./res/charview/" width="180" height="220" scale="1" originX="15" originY="10">
    <palette>
        <!--Colors common for skin/hair/fur/scales/... go here. Can be overriden later-->
        <common>
            <color name="albino">#f2f2e8</color>
            <color name="aqua">#00cccc</color>
            <color name="ashen">#817d79</color>
            <color name="ashen2">#9f948e</color>
            <color name="auburn">#732d26</color>
            <color name="black">#333333</color>
            <color name="blond">#e0c685</color>
            <color name="blonde">#f2e4bf</color>
            <color name="blue">#405fce</color>
            <color name="bronzed">#a89148</color>
            <color name="brown">#664400</color>
            <color name="caramel">#c39350</color>
            <color name="caramel2">#c38c50</color>
            <color name="cerulean">#59cfde</color>
            <color name="cerulean2">#377bc3</color>
            <color name="chocolate">#4a3b2b</color>
            <color name="crimson">#dc143c</color>
            <color name="crystal">#bc81ca</color>
            <color name="dark">#694e44</color>
            <color name="dark2">#352722</color>
            <color name="dusky">#f000f0</color>
            <color name="ebony">#3d3529</color>
            <color name="emerald">#4cc875</color>
            <color name="fair">#edccbf</color>
            <color name="golden">#ffdd00</color>
            <color name="gray">#808080</color>
            <color name="green">#08a108</color>
            <color name="indigo">#4d0080</color>
            <color name="light">#feebd7</color>
            <color name="mahogany">#81473b</color>
            <color name="mahogany2">#672828</color>
            <color name="metallic">#9c9c9c</color>
            <color name="midnight">#30354a</color>
            <color name="olive">#90974e</color>
            <color name="orange">#ffa600</color>
            <color name="peach">#f4c0a4</color>
            <color name="pink">#ffb3b3</color>
            <color name="purple">#7a007a</color>
            <color name="red">#f02c0a</color>
            <color name="red2">#ff0000</color>
            <color name="russet">#aa6546</color>
            <color name="russet2">#793939</color>
            <color name="sable">#d6caa9</color>
            <color name="sanguine">#c03030</color>
            <color name="silky">#ffd6ff</color>
            <color name="silver">#d8e0e9</color>
            <color name="tan">#af8750</color>
            <color name="tan2">#cfaa30</color>
            <color name="tawny">#b97f27</color>
            <color name="turquoise">#1ed9dc</color>
            <color name="white">#e6e6eb</color>
            <color name="yellow">#edef6b</color>
            <color name="aphotic blue-black">#08155e</color>
            <color name="ashen grayish-blue">#93b6c8</color>
            <color name="creamy-white">#f2ebde</color>
            <color name="crimson platinum">#d56c6c</color>
            <color name="dark blue">#3d529e</color>
            <color name="dark gray">#534f59</color>
            <color name="dark green">#36582d</color>
            <color name="deep blue">#1e3667</color>
            <color name="deep red">#742525</color>
            <color name="ghostly pale">#e3deed</color>
            <color name="glacial white">#dee5f2</color>
            <color name="golden blonde">#f5d88a</color>
            <color name="grayish-blue">#b0c9e3</color>
            <color name="iridescent gray">#999999</color>
            <color name="leaf green">#5eba5e</color>
            <color name="light blonde">#ffe78f</color>
            <color name="light blue">#b1c8ec</color>
            <color name="light gray">#dddadd</color>
            <color name="light green">#94f390</color>
            <color name="light grey">#c4d1d9</color>
            <color name="light purple">#e4cdf3</color>
            <color name="lime green">#73df72</color>
            <color name="mediterranean-toned">#ac7339</color>
            <color name="metallic golden">#ddc469</color>
            <color name="metallic silver">#cfedfc</color>
            <color name="midnight black">#171622</color>
            <color name="milky white">#f4dfdc</color>
            <color name="pale white">#ffeac7</color>
            <color name="pale yellow">#eeecaa</color>
            <color name="platinum blonde">#f7f3e8</color>
            <color name="platinum crimson">#ff745c</color>
            <color name="platinum-blonde">#ffe5c7</color>
            <color name="purplish-black">#794474</color>
            <color name="quartz white">#ffffff</color>
            <color name="reddish-orange">#df8453</color>
            <color name="rough gray">#525252</color>
            <color name="sandy blonde">#ebd69e</color>
            <color name="sandy brown">#a28d57</color>
            <color name="sandy-blonde">#e0cd9f</color>
            <color name="shiny black">#1c262c</color>
            <color name="silver blonde">#fcfaf8</color>
            <color name="silver-white">#eff3f6</color>
            <color name="snow white">#f9f9fa</color>
            <color name="yellowish-green">#e1eca7</color>
            <color name="black and yellow">#000000</color>
            <color name="white and black">#eff3f6</color>
        </common>
        <property name="hair" src="hairColor" default="#ffffff">
            <color name="red">#d85741</color>
            <color name="flaxen">#e1ba94</color>
            <color name="brown">#674f42</color>
            <color name="black">#334252</color>
            <color name="gray">#647a7d</color>
            <color name="white">#aeaba3</color>
            <color name="raven">#101728</color>
            <color name="snowy">#dddfe4</color>
        </property>
        <property name="hair2" src="hairColor" default="#ffffff"></property>
        <property name="fur" src="skin.coat.color" default="#ffffff"></property>
        <property name="fur2" src="skin.coat.color2" default="#ffffff"></property>
        <property name="scales" src="skin.coat.color" default="#ffffff"></property>
        <property name="scales2" src="skin.coat.color2" default="#ffffff"></property>
        <property name="chitin" src="skin.coat.color" default="#ffffff"></property>
        <property name="chitin2" src="skin.coat.color2" default="#ffffff"></property>
        <property name="skin" src="skinTone" default="#ffffff">
            <color name="pale">#f2e8e3</color>
        </property>
        <property name="skin2" src="skin.base.color2" default="#ffffff">
            <color name="pale">#f2e8e3</color>
        </property>
        <property name="iris" src="eyes.colour" default="#0000ff">
        </property>
    </palette>
    <colorkeys>
        <key src="#FF88FF" base="hair" transform="lighten(25)"/>
        <key src="#CC00CC" base="hair"/>
        <key src="#880088" base="hair" transform="darken(25)"/>
        <key src="#440044" base="hair" transform="darken(50)"/>
        <key src="#FFFF88" base="hair2" transform="lighten(25)"/>
        <key src="#CCCC00" base="hair2"/>
        <key src="#999900" base="hair2" transform="darken(25)"/>
        <key src="#333300" base="hair2" transform="darken(50)"/>
        <key src="#88FF88" base="fur" transform="lighten(25)"/>
        <key src="#00CC00" base="fur"/>
        <key src="#009900" base="fur" transform="darken(25)"/>
        <key src="#003300" base="fur" transform="darken(50)"/>
        <key src="#AA88FF" base="fur2" transform="lighten(25)"/>
        <key src="#6633CC" base="fur2"/>
        <key src="#442288" base="fur2" transform="darken(25)"/>
        <key src="#220044" base="fur2" transform="darken(50)"/>
        <key src="#8888FF" base="scales" transform="lighten(25)"/>
        <key src="#4444FF" base="scales"/>
        <key src="#0000CC" base="scales" transform="darken(25)"/>
        <key src="#000033" base="scales" transform="darken(50)"/>
        <key src="#AAFFAA" base="scales2" transform="lighten(25)"/>
        <key src="#66CC66" base="scales2"/>
        <key src="#448844" base="scales2" transform="darken(25)"/>
        <key src="#223322" base="scales2" transform="darken(50)"/>
        <key src="#88FFFF" base="chitin" transform="lighten(25)"/>
        <key src="#44CCFF" base="chitin"/>
        <key src="#0099CC" base="chitin" transform="darken(25)"/>
        <key src="#006666" base="chitin" transform="darken(50)"/>
        <key src="#AACCDD" base="chitin2" transform="lighten(25)"/>
        <key src="#77AACC" base="chitin2"/>
        <key src="#4477AA" base="chitin2" transform="darken(25)"/>
        <key src="#114477" base="chitin2" transform="darken(50)"/>
        <key src="#FFE9CC" base="skin" transform="lighten(25)"/>
        <key src="#FACE8D" base="skin"/>
        <key src="#BC9B6D" base="skin" transform="darken(25)"/>
        <key src="#7C6647" base="skin" transform="darken(50)"/>
        <key src="#1C0F0F" base="skin" transform="darken(75)"/>
        <key src="#FFCCCC" base="skin2" transform="lighten(25)"/>
        <key src="#FF9999" base="skin2"/>
        <key src="#BB7777" base="skin2" transform="darken(25)"/>
        <key src="#884444" base="skin2" transform="darken(50)"/>
        <key src="#221111" base="skin2" transform="darken(75)"/>
		<key src="#FF0000" base="iris"/>
		<key src="#AA0000" base="iris" transform="darken(25)"/>
        <!--<key src="#F9A98E" base="nipples"/>-->
        <!--<key src="#FFFFFF" base="sclera"/>-->
        <!--<key src="#0026FF" base="iris"/>-->
    </colorkeys>
    <!--<spritesheet file="char1.png" cellwidth="192" cellheight="192">
        <row>name1,name2,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,breasts/Dfur,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
    </spritesheet>-->


	<!-- LOCATION IN SCREEN AREA -->
    <spritemap file="body.png">
        <cell rect="1,90,49,59" name="torso/human" dx="69" dy="64"/>
        <cell rect="51,90,49,59" name="torso/fur" dx="69" dy="64"/>
        <cell rect="101,90,49,59" name="torso/chitin" dx="69" dy="64"/>
        <cell rect="151,90,49,59" name="torso/bee" dx="69" dy="64"/>
        <cell rect="201,90,49,59" name="torso/orca" dx="69" dy="64"/>
        <cell rect="251,90,49,59" name="torso/pscales" dx="69" dy="64"/>
        <cell rect="301,90,49,59" name="torso/scales" dx="69" dy="64"/>
        <cell rect="351,90,49,59" name="torso/goo" dx="69" dy="64"/>
        <cell rect="401,90,49,59" name="torso/kraken" dx="69" dy="64"/>
        <cell rect="1,150,49,59" name="arms_bg/human" dx="46" dy="64"/>
        <cell rect="51,150,49,59" name="arms_bg/fur" dx="46" dy="64"/>
		<cell rect="552,150,49,59" name="arms_bg/furracoon" dx="46" dy="64"/>
        <cell rect="101,150,49,59" name="arms_bg/chitin" dx="46" dy="64"/>
        <cell rect="151,150,49,59" name="arms_bg/bee" dx="46" dy="64"/>
        <cell rect="201,150,49,59" name="arms_bg/chitin2" dx="46" dy="64"/>
        <cell rect="251,150,49,59" name="arms_bg/orca" dx="46" dy="64"/>
        <cell rect="301,150,49,59" name="arms_bg/pscales" dx="46" dy="64"/>
        <cell rect="351,150,49,59" name="arms_bg/scales" dx="46" dy="64"/>
        <cell rect="401,150,49,59" name="arms_bg/goo" dx="46" dy="64"/>
        <cell rect="1,210,49,59" name="arms/human" dx="94" dy="64"/>
        <cell rect="51,210,49,59" name="arms/fur" dx="94" dy="64"/>
		<cell rect="552,210,49,59" name="arms/furracoon" dx="94" dy="64"/>
        <cell rect="101,210,49,59" name="arms/chitin" dx="94" dy="64"/>
        <cell rect="151,210,49,59" name="arms/bee" dx="94" dy="64"/>
        <cell rect="201,210,49,59" name="arms/chitin2" dx="94" dy="64"/>
        <cell rect="251,210,49,59" name="arms/orca" dx="94" dy="64"/>
        <cell rect="301,210,49,59" name="arms/pscales" dx="94" dy="64"/>
        <cell rect="351,210,49,59" name="arms/scales" dx="94" dy="64"/>
        <cell rect="401,210,49,59" name="arms/goo" dx="94" dy="64"/>
        <cell rect="1,270,49,59" name="hands_bg/fur" dx="46" dy="64"/>
		<cell rect="602,270,49,59" name="hands_bg/furracoon" dx="46" dy="64"/>
        <cell rect="51,270,49,59" name="hands_bg/devil" dx="46" dy="64"/>
        <cell rect="101,270,49,59" name="hands_bg/harpy" dx="46" dy="64"/>
        <cell rect="151,270,49,59" name="hands_bg/kraken" dx="46" dy="64"/>
        <cell rect="201,270,49,59" name="hands_bg/alraune" dx="46" dy="64"/>
        <cell rect="251,270,49,59" name="hands_bg/chitin" dx="46" dy="64"/>
        <cell rect="301,270,49,59" name="hands_bg/chitin2" dx="46" dy="64"/>
        <cell rect="351,270,49,59" name="hands_bg/fire" dx="46" dy="64"/>
        <cell rect="401,270,49,59" name="hands_bg/scales" dx="46" dy="64"/>
        <cell rect="451,270,49,59" name="hands_bg/human" dx="46" dy="64"/>
        <cell rect="501,270,49,59" name="hands_bg/fins-orca" dx="46" dy="64"/>
        <cell rect="551,270,49,59" name="hands_bg/goo" dx="46" dy="64"/>
        <cell rect="1,330,49,59" name="hands/fur" dx="94" dy="64"/>
		<cell rect="602,330,49,59" name="hands/furracoon" dx="94" dy="64"/>
        <cell rect="51,330,49,59" name="hands/devil" dx="94" dy="64"/>
        <cell rect="101,330,49,59" name="hands/harpy" dx="94" dy="64"/>
        <cell rect="151,330,49,59" name="hands/kraken" dx="94" dy="64"/>
        <cell rect="201,330,49,59" name="hands/alraune" dx="94" dy="64"/>
        <cell rect="251,330,49,59" name="hands/chitin" dx="94" dy="64"/>
        <cell rect="301,330,49,59" name="hands/chitin2" dx="94" dy="64"/>
        <cell rect="351,330,49,59" name="hands/fire" dx="94" dy="64"/>
        <cell rect="401,330,49,59" name="hands/scales" dx="94" dy="64"/>
        <cell rect="451,330,49,59" name="hands/human" dx="94" dy="64"/>
        <cell rect="501,330,49,59" name="hands/fins-orca" dx="94" dy="64"/>
        <cell rect="551,330,49,59" name="hands/goo" dx="94" dy="64"/>
        <cell rect="1,390,49,59" name="legs/human" dx="69" dy="115"/>
        <cell rect="51,390,49,59" name="legs/fur" dx="69" dy="115"/>
        <cell rect="101,390,49,59" name="legs/chitin" dx="69" dy="115"/>
        <cell rect="151,390,49,59" name="legs/chitin2" dx="69" dy="115"/>
        <cell rect="201,390,49,59" name="legs/orca" dx="69" dy="115"/>
        <cell rect="251,390,49,59" name="legs/pscales" dx="69" dy="115"/>
        <cell rect="301,390,49,59" name="legs/scales" dx="69" dy="115"/>
        <cell rect="351,390,49,59" name="legs/devil" dx="69" dy="115"/>
        <cell rect="401,390,49,59" name="legs/goo" dx="69" dy="115"/>
        <cell rect="51,450,49,59" name="feet/fur" dx="68" dy="115"/>
        <cell rect="101,450,49,59" name="feet/scales" dx="69" dy="115"/>
        <cell rect="151,450,49,59" name="feet/fire" dx="69" dy="115"/>
        <cell rect="1,520,90,90" name="legs/harpy_human" dx="50" dy="99"/>
        <cell rect="92,520,90,90" name="legs/harpy_fur" dx="50" dy="99"/>
        <cell rect="183,520,90,90" name="legs/harpy_scales" dx="50" dy="99"/>
        <cell rect="274,520,90,90" name="legs/harpy_pscales" dx="50" dy="99"/>
        <cell rect="365,520,90,90" name="legs/harpy_chitin" dx="50" dy="99"/>
        <cell rect="1,611,90,90" name="legs/manticore_sit" dx="50" dy="61"/>
        <cell rect="92,611,90,90" name="legs/manticore_sit_fur" dx="50" dy="61"/>
        <cell rect="183,611,90,90" name="legs/manticore_sit_scales" dx="50" dy="61"/>
        <cell rect="274,611,90,90" name="legs/manticore_sit_pscales" dx="50" dy="61"/>
        <cell rect="365,611,90,90" name="legs/manticore_sit_chitin" dx="50" dy="61"/>
        <cell rect="1,702,90,90" name="arms/manticore_sit" dx="50" dy="61"/>
        <cell rect="92,702,90,90" name="arms/manticore_sit_fur" dx="50" dy="61"/>
        <cell rect="183,702,90,90" name="arms/manticore_sit_scales" dx="50" dy="61"/>
        <cell rect="274,702,90,90" name="arms/manticore_sit_pscales" dx="50" dy="61"/>
        <cell rect="365,702,90,90" name="arms/manticore_sit_chitin" dx="50" dy="61"/>
    </spritemap>
    <spritemap file="extra.png">
        <cell rect="2,55,147,128" name="legs_bg/alraune" dx="24" dy="82"/>
        <cell rect="1,188,173,156" name="legs_bg/liliraune" dx="-3" dy="58"/>
        <cell rect="9,351,175,119" name="legs_bg/drider" dx="21" dy="64"/>
        <cell rect="226,325,143,107" name="legs_bg/centaur" dx="47" dy="93"/>
        <cell rect="131,491,117,117" name="legs/kraken" dx="35" dy="94"/>
        <cell rect="251,450,118,158" name="legs/scylla" dx="34" dy="54"/>
        <cell rect="255,230,125,88" name="legs_bg/cattaur" dx="71" dy="101"/>
		<cell rect="382,230,125,88" name="legs_bg/reptaur" dx="71" dy="101"/>
		<cell rect="371,325,175,119" name="legs_bg/crabtaur" dx="21" dy="64"/>
		<cell rect="547,325,175,119" name="legs_bg/bugtaur" dx="21" dy="64"/>
        <cell rect="201,101,130,108" name="legs/naga" dx="32" dy="96"/>
		<cell rect="333,101,130,108" name="legs/melkie" dx="32" dy="96"/>
        <cell rect="132,611,125,69" name="legs/gooblob" dx="31" dy="102"/>
        <cell rect="260,620,21,28" name="neck/goocore" dx="85" dy="67"/>
        <cell rect="162,59,54,31" name="neck/manticore" dx="67" dy="46"/>
        <cell rect="218,59,54,31" name="neck/weasel" dx="67" dy="52"/>
    </spritemap>
    <spritemap file="hair.png">
        <cell rect="1,70,59,65" name="hair/0" dx="65" dy="21"/>
        <cell rect="1,136,59,65" name="hair_bg/0" dx="65" dy="21"/>
		<cell rect="362,350,89,164" name="hair_bg/02" dx="50" dy="4"/>
        <cell rect="61,70,59,65" name="hair/feather" dx="65" dy="21"/>
        <cell rect="61,136,59,65" name="hair_bg/feather" dx="65" dy="21"/>
        <cell rect="121,70,59,65" name="hair/gorgon" dx="65" dy="21"/>
        <cell rect="121,136,59,65" name="hair_bg/gorgon" dx="65" dy="21"/>
        <cell rect="1,251,89,98" name="hair/slime" dx="50" dy="4"/>
        <cell rect="91,251,89,98" name="hair_bg/slime2" dx="50" dy="4"/>
        <cell rect="1,350,89,98" name="hair/raiju" dx="50" dy="4"/>
        <cell rect="91,350,89,164" name="hair_bg/raiju3" dx="50" dy="4"/>
		<cell rect="181,350,89,98" name="hair/hellcat" dx="50" dy="4"/>
        <cell rect="271,350,89,164" name="hair_bg/hellcat" dx="50" dy="4"/>
    </spritemap>
    <spritemap file="head.png">
        <cell rect="1,70,29,32" name="head/human" dx="80" dy="37"/>
        <cell rect="31,70,29,32" name="head/fur" dx="80" dy="37"/>
        <cell rect="61,70,29,32" name="head/pscales" dx="80" dy="37"/>
        <cell rect="91,70,29,32" name="head/scales" dx="80" dy="37"/>
        <cell rect="121,70,29,32" name="head/chitin" dx="80" dy="37"/>
        <cell rect="151,70,29,32" name="head/bee" dx="80" dy="37"/>
        <cell rect="181,70,29,32" name="head/orca" dx="80" dy="37"/>
        <cell rect="211,70,29,32" name="head/goo" dx="80" dy="37"/>
        <cell rect="1,110,29,32" name="face/human" dx="80" dy="37"/>
        <cell rect="31,110,29,32" name="face/human_fang" dx="80" dy="37"/>
        <cell rect="61,110,29,32" name="face/fur" dx="80" dy="37"/>
        <cell rect="91,110,29,32" name="face/spider" dx="80" dy="37"/>
        <cell rect="121,110,29,32" name="face/insect" dx="80" dy="37"/>
        <cell rect="151,110,29,32" name="face/mouse" dx="80" dy="37"/>
        <cell rect="181,110,29,32" name="face/orca" dx="80" dy="37"/>
        <cell rect="211,110,29,32" name="face/shark" dx="80" dy="37"/>
        <cell rect="241,110,29,32" name="face/reptile" dx="80" dy="37"/>
        <cell rect="271,110,29,32" name="face/fur2" dx="80" dy="37"/>
        <cell rect="301,110,29,32" name="face/racoon" dx="80" dy="37"/>
        <cell rect="331,110,29,32" name="face/racoon_mask" dx="80" dy="37"/>
        <cell rect="361,110,29,32" name="face/goo" dx="80" dy="37"/>
		<cell rect="391,110,29,32" name="face/bunny" dx="80" dy="37"/>
		<cell rect="421,110,29,32" name="face/cheshire" dx="80" dy="37"/>
        <cell rect="1,150,29,32" name="eyes/human" dx="80" dy="37"/>
        <cell rect="31,150,29,32" name="eyes/devil" dx="80" dy="37"/>
        <cell rect="61,150,29,32" name="eyes/cat" dx="80" dy="37"/>
        <cell rect="91,150,29,32" name="eyes/spider" dx="80" dy="37"/>
        <cell rect="121,150,29,32" name="eyes/sandtrap" dx="80" dy="37"/>
        <cell rect="151,150,29,32" name="eyes/manticore" dx="80" dy="37"/>
        <cell rect="181,150,29,32" name="eyes/orca" dx="80" dy="37"/>
        <cell rect="211,150,29,32" name="eyes/raiju" dx="80" dy="37"/>
		<cell rect="241,150,29,32" name="eyes/infernal" dx="80" dy="37"/>
        <cell rect="1,190,29,32" name="ears_bg/human" dx="80" dy="37"/>
        <cell rect="31,190,29,32" name="ears/fur" dx="80" dy="37"/>
        <cell rect="61,190,59,32" name="ears_bg/elfin" dx="65" dy="37"/>
        <cell rect="61,223,59,32" name="ears/elfin" dx="65" dy="37"/>
        <cell rect="121,190,59,32" name="ears_bg/goat" dx="65" dy="37"/>
        <cell rect="121,223,59,32" name="ears/goat" dx="65" dy="37"/>
        <cell rect="121,256,59,32" name="ears_bg/dragon" dx="65" dy="37"/>
        <cell rect="121,289,59,32" name="ears/dragon" dx="65" dy="37"/>
        <cell rect="181,190,29,65" name="ears_bg/fox" dx="80" dy="4"/>
        <cell rect="181,256,29,65" name="ears/fox" dx="80" dy="4"/>
        <cell rect="211,190,29,65" name="ears_bg/wolf" dx="80" dy="4"/>
        <cell rect="211,256,29,65" name="ears/wolf" dx="80" dy="4"/>
        <cell rect="241,190,29,65" name="ears_bg/cat" dx="80" dy="4"/>
        <cell rect="241,256,29,65" name="ears/cat" dx="80" dy="4"/>
        <cell rect="271,190,29,65" name="ears_bg/mouse" dx="80" dy="4"/>
        <cell rect="271,256,29,65" name="ears/mouse" dx="80" dy="4"/>
        <cell rect="301,190,89,65" name="ears_bg/orca" dx="50" dy="37"/>
        <cell rect="301,256,89,65" name="ears/orca" dx="50" dy="37"/>
        <cell rect="391,190,59,32" name="ears_bg/naga" dx="65" dy="37"/>
        <cell rect="391,223,59,32" name="ears/naga" dx="65" dy="37"/>
        <cell rect="451,190,59,65" name="ears_bg/bunny" dx="65" dy="4"/>
        <cell rect="451,256,59,65" name="ears/bunny" dx="65" dy="4"/>
        <cell rect="511,190,89,65" name="ears_bg/weasel" dx="50" dy="4"/>
        <cell rect="511,256,89,65" name="ears/weasel" dx="50" dy="4"/>
		<cell rect="671,190,59,65" name="ears_bg/horse" dx="65" dy="37"/>
        <cell rect="1,330,59,65" name="horns_bg/orchid" dx="65" dy="4"/>
        <cell rect="1,396,59,65" name="horns/orchid" dx="65" dy="4"/>
        <cell rect="61,330,59,65" name="horns_bg/devil" dx="65" dy="4"/>
        <cell rect="61,396,59,65" name="horns/devil" dx="65" dy="4"/>
        <cell rect="121,330,59,65" name="horns_bg/cow" dx="65" dy="4"/>
        <cell rect="121,396,59,65" name="horns/cow" dx="65" dy="4"/>
        <cell rect="181,330,29,65" name="horns/2small" dx="80" dy="4"/>
        <cell rect="211,330,29,65" name="horns/2large" dx="80" dy="4"/>
        <cell rect="241,330,59,65" name="horns_bg/kraken" dx="65" dy="4"/>
        <cell rect="301,330,59,65" name="horns_bg/demon" dx="65" dy="4"/>
        <cell rect="361,330,59,65" name="horns_bg/dragon" dx="65" dy="4"/>
        <cell rect="361,396,59,65" name="horns/dragon" dx="65" dy="4"/>
		<cell rect="421,330,29,32" name="horns/unicorn" dx="80" dy="37"/>
        <cell rect="421,363,29,32" name="horns/bicorn" dx="80" dy="37"/>
		<cell rect="481,363,29,32" name="horns/2oni" dx="80" dy="37"/>
        <cell rect="1,470,59,65" name="antennae/bee" dx="65" dy="4"/>
    </spritemap>
    <spritemap file="lewd.png">
        <cell rect="11,80,49,29" name="breasts/0" dx="69" dy="68"/>
        <cell rect="11,110,49,29" name="breasts/Bhuman" dx="69" dy="68"/>
        <cell rect="61,110,49,29" name="breasts/Bfur" dx="69" dy="68"/>
        <cell rect="111,110,49,29" name="breasts/Bchitin" dx="69" dy="68"/>
        <cell rect="161,110,49,29" name="breasts/Bbee" dx="69" dy="68"/>
        <cell rect="211,110,49,29" name="breasts/Bpscales" dx="69" dy="68"/>
        <cell rect="261,110,49,29" name="breasts/Bscales" dx="69" dy="68"/>
        <cell rect="311,110,49,29" name="breasts/Borca" dx="69" dy="68"/>
        <cell rect="361,110,49,29" name="breasts/Bgoo" dx="69" dy="68"/>
        <cell rect="11,140,49,29" name="breasts/Dhuman" dx="69" dy="68"/>
        <cell rect="61,140,49,29" name="breasts/Dfur" dx="69" dy="68"/>
        <cell rect="111,140,49,29" name="breasts/Dchitin" dx="69" dy="68"/>
        <cell rect="161,140,49,29" name="breasts/Dbee" dx="69" dy="68"/>
        <cell rect="211,140,49,29" name="breasts/Dpscales" dx="69" dy="68"/>
        <cell rect="261,140,49,29" name="breasts/Dscales" dx="69" dy="68"/>
        <cell rect="311,140,49,29" name="breasts/Dorca" dx="69" dy="68"/>
        <cell rect="361,140,49,29" name="breasts/Dgoo" dx="69" dy="68"/>
    </spritemap>
    <spritemap file="tails.png">
        <cell rect="1,71,168,139" name="tail/manticore" dx="10" dy="40"/>
		<cell rect="1,71,168,139" name="tail/manticore_taur" dx="185" dy="40"/>
        <cell rect="1,211,83,139" name="tail/orca" dx="78" dy="39"/>
		<cell rect="1,211,83,139" name="tail/orca_taur" dx="185" dy="40"/>
        <cell rect="86,211,83,139" name="tail/mouse" dx="85" dy="40"/>
		<cell rect="86,211,83,139" name="tail/mouse_taur" dx="185" dy="40"/>
        <cell rect="170,211,83,139" name="tail/mouse_fire" dx="85" dy="40"/>
		<cell rect="170,211,83,139" name="tail/mouse_fire_taur" dx="185" dy="40"/>
        <cell rect="255,211,83,139" name="tail/cat" dx="85" dy="40"/>
		<cell rect="255,211,83,139" name="tail/cat_taur" dx="185" dy="40"/>
        <cell rect="339,211,83,139" name="tail/cat2" dx="85" dy="40"/>
		<cell rect="339,211,83,139" name="tail/cat2_taur" dx="185" dy="40"/>
		<cell rect="507,211,83,139" name="tail/horse" dx="85" dy="40"/>
		<cell rect="507,211,83,139" name="tail/horse_taur" dx="185" dy="40"/>
        <cell rect="1,351,168,69" name="tail/reptile" dx="10" dy="90"/>
		<cell rect="1,351,168,69" name="tail/reptile_taur" dx="185" dy="40"/>
        <cell rect="170,351,168,69" name="tail/demon" dx="10" dy="90"/>
		<cell rect="170,351,168,69" name="tail/demon_taur" dx="185" dy="40"/>
		<cell rect="339,351,168,69" name="tail/gargoyle_axe" dx="10" dy="90"/>
		<cell rect="339,421,168,69" name="tail/gargoyle_mace" dx="10" dy="90"/>
        <cell rect="1,421,168,69" name="tail_fg/reptile_fire" dx="10" dy="90"/>
		<cell rect="1,421,168,69" name="tail/reptile_fire_taur" dx="185" dy="40"/>
        <cell rect="170,421,168,69" name="tail/cow" dx="10" dy="90"/>
		<cell rect="170,421,168,69" name="tail/cow_taur" dx="185" dy="40"/>
        <cell rect="1,491,83,69" name="tail/bunny" dx="85" dy="90"/>
		<cell rect="1,491,83,69" name="tail/bunny_taur" dx="185" dy="40"/>
        <cell rect="86,491,83,69" name="tail/goat" dx="85" dy="90"/>
		<cell rect="86,491,83,69" name="tail/goat_taur" dx="185" dy="40"/>
        <cell rect="170,491,83,69" name="tail/harpy" dx="85" dy="90"/>
		<cell rect="170,491,83,69" name="tail/harpy_taur" dx="185" dy="40"/>
        <cell rect="1,561,83,139" name="tail/fox1" dx="85" dy="40"/>
		<cell rect="1,561,83,139" name="tail/fox1_taur" dx="185" dy="40"/>
        <cell rect="86,561,83,139" name="tail/fox2" dx="85" dy="40"/>
		<cell rect="86,561,83,139" name="tail/fox2_taur" dx="185" dy="40"/>
        <cell rect="170,561,83,139" name="tail/bee_abdomen" dx="85" dy="40"/>
		<cell rect="170,561,83,139" name="tail/bee_taur" dx="185" dy="40"/>
        <cell rect="255,561,83,139" name="tail/spider" dx="85" dy="40"/>
		<cell rect="255,561,83,139" name="tail/spider_taur" dx="185" dy="40"/>